### ISSUE TITLE
Missing screenshot

### ISSUE THREAD

**Issue by sistematico** [budRich/i3ass#1]
Missing image on: https://github.com/budRich/i3ass/blob/master/README.md

**Comment by budRich** [comment]
hi sistematico. I know there are some image links that are broken. The READMES is actually from my homepage, i just removed the yaml and renamed them. I will look in to that today. But in the README, you linked (the repos readme) there was never a screenshot in the first place. Are you suggesting I add some screenshots? I think I will do that.

Please let me know if you find anything else that isn't working or can be improved.

// bud

**Comment by sistematico** [comment]
Sorry.

https://github.com/budRich/i3ass/blob/master/i3gw/README.md

**Comment by budRich** [comment]
fixed now!
